IF NOT EXISTS (SELECT NAME FROM sys.objects WHERE TYPE = 'P' AND NAME = 'BKO_INV_CancelAccounting')
  BEGIN
	EXEC('CREATE PROCEDURE [dbo].[BKO_INV_CancelAccounting] AS RETURN')
END
GO

Create PROCEDURE [dbo].[BKO_INV_CancelAccounting]
@COD_ASIENTO VARCHAR(80),
@ID_EMPRESA int,
@FEC_PERIODO date,
@ESTADO VARCHAR(5),
@USER_MODIFICA INT,
@FEC_MODIFICA Date
AS
BEGIN
	
	BEGIN TRAN
	
		IF (SELECT IND_ESTADO FROM CN_ASIENTO WHERE COD_ASIENTO = @COD_ASIENTO AND ID_EMPRESA = @ID_EMPRESA) = 'Apli'
		BEGIN
		
			DECLARE @NUM_CUENTA varchar(50), 
				@IND_DEBCRE varchar(5),
				@MONTO_MOV float,
				@NUM_CTA_MADRE varchar(50)

			SELECT NUM_CUENTA, IND_DEBCRE, SUM(MONTO_MOV) AS MONTO_MOV, 0 AS BANDERA
			INTO #CN_ASIENTO_DETALLE_TEMP
			FROM CN_ASIENTO_DETALLE 
			WHERE COD_ASIENTO = @COD_ASIENTO
			AND ID_EMPRESA = @ID_EMPRESA
			GROUP BY NUM_CUENTA, IND_DEBCRE

			WHILE(SELECT COUNT(1) FROM #CN_ASIENTO_DETALLE_TEMP WHERE BANDERA = 0) > 0
			BEGIN

				SELECT TOP 1
				@NUM_CUENTA = NUM_CUENTA,
				@MONTO_MOV = MONTO_MOV,
				@IND_DEBCRE = IND_DEBCRE
				FROM #CN_ASIENTO_DETALLE_TEMP
				WHERE BANDERA = 0

				UPDATE #CN_ASIENTO_DETALLE_TEMP
				SET BANDERA = 1
				WHERE NUM_CUENTA = @NUM_CUENTA
				AND IND_DEBCRE = @IND_DEBCRE
				AND BANDERA = 0

				SELECT @NUM_CTA_MADRE = NUM_CTA_MADRE FROM CN_CUENTA
				WHERE ID_EMPRESA = @ID_EMPRESA AND NUM_CUENTA = @NUM_CUENTA
		
				IF (@IND_DEBCRE = 'D') 
					BEGIN
					UPDATE CN_CUENTA 
					SET MONTO_DEBER = MONTO_DEBER - @MONTO_MOV
					WHERE ID_EMPRESA = @ID_EMPRESA AND NUM_CUENTA = @NUM_CUENTA
				END
				ELSE
				BEGIN
					UPDATE CN_CUENTA 
					SET MONTO_HABER = MONTO_HABER - @MONTO_MOV
					WHERE ID_EMPRESA = @ID_EMPRESA AND NUM_CUENTA = @NUM_CUENTA
				END

				WHILE (@NUM_CTA_MADRE) <> 'No' 
				BEGIN

					IF (@IND_DEBCRE = 'D') 
					BEGIN
						UPDATE CN_CUENTA 
						SET MONTO_DEBER = MONTO_DEBER - @MONTO_MOV
						WHERE ID_EMPRESA = @ID_EMPRESA AND NUM_CUENTA = @NUM_CTA_MADRE
					END
					ELSE
					BEGIN
						UPDATE CN_CUENTA 
						SET MONTO_HABER = MONTO_HABER - @MONTO_MOV
						WHERE ID_EMPRESA = @ID_EMPRESA AND NUM_CUENTA = @NUM_CTA_MADRE
					END

					SELECT @NUM_CTA_MADRE = NUM_CTA_MADRE FROM CN_CUENTA
					WHERE ID_EMPRESA = @ID_EMPRESA AND NUM_CUENTA = @NUM_CTA_MADRE

				END

			END
	
		END

		UPDATE CN_ASIENTO SET IND_ESTADO = @ESTADO, USER_MODIFICA = @USER_MODIFICA, FEC_MODIFICA = @FEC_MODIFICA
		WHERE COD_ASIENTO = @COD_ASIENTO AND ID_EMPRESA = @ID_EMPRESA

		IF(SELECT COUNT(1) FROM CN_ASIENTO_PROVEEDOR_PAGO WHERE COD_ASIENTO_PAGO = @COD_ASIENTO) > 0
		BEGIN
			IF(SELECT COUNT(1) FROM CN_ASIENTO_PROVEEDOR WHERE COD_ASIENTO = @COD_ASIENTO) > 0
			BEGIN
		
				UPDATE CN_ASIENTO_PROVEEDOR
				SET ESTADO = 'Anulado'
				WHERE COD_ASIENTO IN (SELECT COD_ASIENTO_FACTURA FROM CN_ASIENTO_PROVEEDOR_PAGO WHERE COD_ASIENTO_PAGO = @COD_ASIENTO)			
		
			END
			ELSE
			BEGIN

				DECLARE @COD_ASIENTO_PAGO varchar(80), @COD_ASIENTO_FACTURA varchar(80), @SALDO_ANTERIOR decimal(18,2), @SALDO_ACTUAL decimal(18,2),@COD_ASIENTO_PAGO_AGREGAR_SALDO decimal(18,2)

				SELECT  @COD_ASIENTO_PAGO = @COD_ASIENTO

				UPDATE CN_ASIENTO_PROVEEDOR_PAGO 
				SET ESTADO_PAGO = 'Anulado'
				WHERE COD_ASIENTO_PAGO = @COD_ASIENTO_PAGO

				UPDATE CN_ASIENTO_PROVEEDOR
				SET ESTADO = 'Pendiente'
				WHERE COD_ASIENTO IN (SELECT COD_ASIENTO_FACTURA FROM CN_ASIENTO_PROVEEDOR_PAGO WHERE COD_ASIENTO_PAGO = @COD_ASIENTO_PAGO)

				UPDATE CN_ASIENTO_PROVEEDOR_PAGO
				SET ESTADO_PAGO = 'Pendiente'
				WHERE COD_ASIENTO_FACTURA IN (SELECT COD_ASIENTO_FACTURA FROM CN_ASIENTO_PROVEEDOR_PAGO WHERE COD_ASIENTO_PAGO = @COD_ASIENTO_PAGO)
				AND ESTADO_PAGO != 'Anulado'

				SELECT *,'P' AS BANDERA
				INTO #PROVEEDOR_PAGO
				FROM CN_ASIENTO_PROVEEDOR_PAGO 
				WHERE COD_ASIENTO_PAGO = @COD_ASIENTO_PAGO

				WHILE (SELECT COUNT(1) FROM #PROVEEDOR_PAGO WHERE BANDERA = 'P') < 0
				BEGIN

					SELECT TOP 1 @COD_ASIENTO_FACTURA = COD_ASIENTO_FACTURA, @SALDO_ANTERIOR = SALDO_ANTERIOR - SALDO_ACTUAL 
					FROM #PROVEEDOR_PAGO 
					WHERE COD_ASIENTO_PAGO = @COD_ASIENTO_PAGO AND BANDERA = 'P'

					SELECT TOP 1 @SALDO_ACTUAL = SALDO_ACTUAL,@COD_ASIENTO_PAGO_AGREGAR_SALDO = COD_ASIENTO_PAGO  
					FROM CN_ASIENTO_PROVEEDOR_PAGO WHERE COD_ASIENTO_FACTURA = @COD_ASIENTO_FACTURA AND COD_ASIENTO_PAGO != @COD_ASIENTO_PAGO AND ESTADO_PAGO != 'Anulado'
					ORDER BY CONVERT(int,COD_ASIENTO_PAGO) DESC

					UPDATE CN_ASIENTO_PROVEEDOR_PAGO
					SET ESTADO_PAGO = 'Pendiente', SALDO_ACTUAL = SALDO_ACTUAL + @SALDO_ANTERIOR
					WHERE COD_ASIENTO_PAGO = @COD_ASIENTO_PAGO_AGREGAR_SALDO

					UPDATE #PROVEEDOR_PAGO 
					SET BANDERA = 'A'
					WHERE BANDERA = 'P' AND COD_ASIENTO_FACTURA = @COD_ASIENTO_FACTURA 
					AND COD_ASIENTO_PAGO = @COD_ASIENTO_PAGO 
					AND ESTADO_PAGO != 'Anulado'

				END

			END
		END

		DECLARE @MAXCOD_ASIENTO int

		SELECT @MAXCOD_ASIENTO = MAX(CONVERT(int,COD_ASIENTO)) + 1 FROM CN_ASIENTO
		
		INSERT INTO CN_ASIENTO
		SELECT [ID_EMPRESA] ,@MAXCOD_ASIENTO,[FEC_PERIODO], [FEC_ASIENTO],
		CONVERT(varchar(200),'Reversado- ' + [DET_ASIENTO]),'Apli',[COD_SISTEMA_ORIGEN],[IND_SISTEMA],CONVERT(date,GETDATE()),[USER_INCLUSION],[FEC_MODIFICA],[USER_MODIFICA],[CUADRADO],'A'
		FROM CN_ASIENTO WHERE COD_ASIENTO = @COD_ASIENTO

		INSERT INTO CN_ASIENTO_DETALLE
		SELECT [ID_EMPRESA],@MAXCOD_ASIENTO,[FEC_PERIODO],
		[NUM_LINEA_ASIENTO],[MONTO_MOV],[NUM_CUENTA],CASE WHEN [IND_DEBCRE] = 'D' THEN 'C' ELSE 'D' END,[MON_TIPO_CAMBIO],[MONTO_ORIGINAL],[MONEDA_ORIGINAL],[COD_CLIENTE]
		FROM CN_ASIENTO_DETALLE WHERE COD_ASIENTO = @COD_ASIENTO

		INSERT INTO [dbo].[CN_ASIENTO_REVERSADO]
			   ([COD_ASIENTO]
			   ,[COD_ASIENTO_REVERSADO])
		 VALUES
			   (@MAXCOD_ASIENTO
			   ,@COD_ASIENTO)
	
	COMMIT TRAN

END


IF NOT EXISTS (SELECT NAME FROM sys.objects WHERE TYPE = 'P' AND NAME = 'BKO_INV_CancelPayment')
  BEGIN
	EXEC('CREATE PROCEDURE [dbo].[BKO_INV_CancelPayment] AS RETURN')
END
GO

ALTER PROCEDURE [dbo].[BKO_INV_CancelPayment] 
@ID_EMPRESA AS INT,
@ID_PAGO AS INT,
@USUARIO AS VARCHAR(50)
AS
BEGIN

BEGIN TRAN

	DECLARE @COD_ASIENTO varchar(80)
	DECLARE @FECHA AS DATE
	DECLARE @FECHA_FACTURA AS DATE
	DECLARE @CANTIDAD AS INT
	DECLARE @MONTOLOCAL AS FLOAT
	DECLARE @MONTODOLAR AS FLOAT
	SET @FECHA = GETDATE()
	DECLARE @ID_USUARIO AS INT
	DECLARE @TIPOCAMBIO AS DECIMAL(18,2)
	DECLARE @MONTOPAGADO AS FLOAT
	DECLARE @MONTOPAGADOLOCAL AS FLOAT
	DECLARE @MONTOPAGADODOLAR AS FLOAT
	DECLARE @MONEDA AS INT, @COD_CLIENTE varchar(200)


	DECLARE @ESTADO_CUSTOMCLEARED AS INT

	SELECT @ESTADO_CUSTOMCLEARED = EST_SCANNER FROM PAR_PARAMETRO

	SELECT @ID_USUARIO = ID FROM USU_USUARIO WHERE USUARIO = @USUARIO

	SELECT @COD_ASIENTO = COD_ASIENTO FROM CN_ASIENTO_PAGO 
	WHERE  ID_EMPRESA = @ID_EMPRESA AND ID_PAGO = @ID_PAGO

	SELECT TOP 1 @TIPOCAMBIO = MON_TIPO_CAMBIO, @COD_CLIENTE = COD_CLIENTE FROM CN_ASIENTO_DETALLE
	WHERE ID_EMPRESA = @ID_EMPRESA AND COD_ASIENTO = @COD_ASIENTO

	UPDATE FC_PAGO
	SET ESTADO = 1 -- ANULADO
	WHERE ID_EMPRESA = @ID_EMPRESA AND ID = @ID_PAGO

	UPDATE FC_CAJA_MOVIMIENTOS
	SET ESTADO = 1 -- ANULADO
	WHERE ID_EMPRESA = @ID_EMPRESA AND PAGO_ID = @ID_PAGO

	SELECT @CANTIDAD = COUNT(1) 
	FROM FC_PAGOFACTURAS 
	WHERE IDPAGO = @ID_PAGO


	IF (@CANTIDAD = 1)
	BEGIN
	--print 'entro'
		
		SELECT @MONTOLOCAL = TOTALLOCAL, @MONTODOLAR = TOTAL, @MONTOPAGADO = PAGADO, @MONEDA = COD_MONEDA 
		FROM FC_PAGO WHERE ID = @ID_PAGO
		
		SELECT @FECHA_FACTURA = FECHA, @TIPOCAMBIO = TIPO_CAMBIO_VENTA FROM FC_FACTURA WHERE N_FACTURA IN (SELECT N_FACTURA FROM FC_PAGOFACTURAS WHERE IDPAGO = @ID_PAGO)


		IF(@MONEDA = 188)
		BEGIN
			SET @MONTOPAGADOLOCAL = @MONTOPAGADO
			SET @MONTOPAGADODOLAR = Convert(decimal(18,2), @MONTOPAGADO / @TIPOCAMBIO)

		END
		ELSE
		BEGIN
			SET @MONTOPAGADODOLAR = @MONTOPAGADO
			SET @MONTOPAGADOLOCAL = Convert(decimal(18,2), @MONTOPAGADO * @TIPOCAMBIO)

		END
		
		PRINT @MONTOPAGADODOLAR
		PRINT @MONTOPAGADOLOCAL

		UPDATE FC_FACTURA
		SET ESTADO = 0, -- PENDIENTE DE PAGAR
		SALDO = SALDO + @MONTOPAGADODOLAR, SALDOLOCAL = SALDOLOCAL + @MONTOPAGADOLOCAL--, PAGADO = TOTAL-SALDO--, PAGADO = PAGADO - @MONTOPAGADODOLAR -- REGRESO EL SALDO DE LA FACTURA
		WHERE N_FACTURA IN
		(
			SELECT N_FACTURA FROM FC_PAGOFACTURAS
			WHERE ID_EMPRESA = @ID_EMPRESA AND IDPAGO = @ID_PAGO  
		)

		UPDATE FC_FACTURA
		SET PAGADO = TOTAL-SALDO -- REGRESO EL SALDO DE LA FACTURA
		WHERE N_FACTURA IN
		(
			SELECT N_FACTURA FROM FC_PAGOFACTURAS
			WHERE ID_EMPRESA = @ID_EMPRESA AND IDPAGO = @ID_PAGO  
		)

	END
	ELSE
	BEGIN
		UPDATE FC_FACTURA
		SET ESTADO = 0, -- PENDIENTE DE PAGAR
		SALDO = TOTAL, SALDOLOCAL = TOTALLOCAL, PAGADO = 0 -- REGRESO EL SALDO DE LA FACTURA
		
		WHERE N_FACTURA IN
		(
			SELECT N_FACTURA FROM FC_PAGOFACTURAS
			WHERE ID_EMPRESA = @ID_EMPRESA AND IDPAGO = @ID_PAGO  
		)
	END

	-- Se regresa el paquete a custom cleared
	UPDATE PAQ_PAQUETE
	SET EST_ID = @ESTADO_CUSTOMCLEARED 
	WHERE NUMERO IN
	(
		SELECT NUMERO FROM FC_FACTURAPAQUETES 
		WHERE N_FACTURA IN
		(		
			SELECT N_FACTURA FROM FC_PAGOFACTURAS
			WHERE ID_EMPRESA = @ID_EMPRESA AND IDPAGO = @ID_PAGO  
		)
	)


IF(@ID_EMPRESA = 2)
BEGIN
	EXECUTE BKO_INV_CancelAccounting @COD_ASIENTO, @ID_EMPRESA, @FECHA, 'Anu', @ID_USUARIO, @FECHA
END

COMMIT TRAN

END

IF NOT EXISTS (SELECT NAME FROM sys.objects WHERE TYPE = 'P' AND NAME = 'BKO_INV_ElectronicInvoiceExists')
  BEGIN
	EXEC('CREATE PROCEDURE [dbo].[BKO_INV_ElectronicInvoiceExists] AS RETURN')
END
GO

ALTER PROCEDURE [dbo].[BKO_INV_ElectronicInvoiceExists]
@N_FACTURA int,
@ID_EMPRESA int
AS
BEGIN
	
	set NOCOUNT ON;

	SELECT COUNT(1) Cantidad FROM FC_FACTURA_ELECTRONICA 
	WHERE N_FACTURA = @N_FACTURA AND ID_EMPRESA = @ID_EMPRESA AND Procesada = 1 AND Respuesta = 'OK-aceptado' AND NumeroConsecutivoTipoComprobante != '03'

END


IF NOT EXISTS (SELECT NAME FROM sys.objects WHERE TYPE = 'P' AND NAME = 'BKO_INV_CancelInvoice')
  BEGIN
	EXEC('CREATE PROCEDURE [dbo].[BKO_INV_CancelInvoice] AS RETURN')
END
GO

ALTER PROCEDURE [dbo].[BKO_INV_CancelInvoice] 
@ID_EMPRESA AS INT,
@N_FACTURA AS INT,
@USUARIO AS VARCHAR(50)
AS
BEGIN

	DECLARE @ID_ASIENTO AS INT
	DECLARE @FECHA AS DATE
	SET @FECHA = GETDATE()
	DECLARE @ID_USUARIO AS INT
	SELECT @ID_USUARIO ID FROM USU_USUARIO WHERE USUARIO = @USUARIO

	SELECT @ID_ASIENTO = COD_ASIENTO FROM CN_ASIENTO_FACTURA 
	WHERE  ID_EMPRESA = @ID_EMPRESA AND  N_FACTURA = @N_FACTURA

	UPDATE FC_FACTURA
	SET ESTADO = 1 --ANULADA
	WHERE ID_EMPRESA = @ID_EMPRESA AND N_FACTURA = @N_FACTURA

	UPDATE PAQ_PAQUETE SET
	ESTADOFACTURA = 1 -- PENDIENTE DE FACTURAR
	WHERE NUMERO IN
	(
		SELECT NUMERO FROM FC_FACTURAPAQUETES
		WHERE N_FACTURA = @N_FACTURA AND ID_EMPRESA = @ID_EMPRESA
	)

	UPDATE ENM_ENCABEZADO_MANIFIESTO 
	SET ESTADOFACTURA = 1
	WHERE ESTADOFACTURA = 2 
	AND ID IN 
	(
		SELECT D.ENM_ID 
		FROM FC_FACTURAPAQUETES FP 
		INNER JOIN PAQ_PAQUETE P
		ON FP.NUMERO = P.NUMERO
		INNER JOIN DEM_DETALLE_MANIFIESTO D
		ON D.PAQ_ID = P.ID
		WHERE FP.N_FACTURA = @N_FACTURA AND FP.ID_EMPRESA = @ID_EMPRESA
	)
		
--Factura Electrónica

IF(@ID_EMPRESA = 2 )
BEGIN

	INSERT INTO FC_FACTURA_ELECTRONICA_ANULADA
	SELECT [N_FACTURA],[ID_EMPRESA],[Procesada],[NumeroConsecutivoSucursal],[NumeroConsecutivoPuntodeVenta],[NumeroConsecutivoTipoComprobante],[NumeroConsecutivoNumeroComprobanteElectronico]
	,[ClaveCodigoPais],[ClaveFechaFactura],[ClaveSituacionComprobante],[CodigoActividad],[Clave],[NumeroConsecutivo],[FechaEmision],[EmisorNombre],[EmisorTipo],[EmisorNumero]
	,[EmisorProvincia],[EmisorCanton],[EmisorDistrito],[EmisorBarrio],[EmisorOtrasSenas],[EmisorCodigoPais],[EmisorNumTelefono],[EmisorCorreoElectronico],[ReceptorNombre]
	,[ReceptorTipo],[ReceptorNumero],[ReceptorIdentificacionExtranjero],[ReceptorProvincia],[ReceptorCanton],[ReceptorDistrito],[ReceptorBarrio],[ReceptorOtrasSenas]
	,[ReceptorCorreoElectronico],[CondicionVenta],[PlazoCredito],[MedioPago],[LineaDetalleNumeroLinea],[LineaDetallePartidaArancelaria],[LineaDetalleCodigo],[LineaDetalleCodigoComercialTipo]
	,[LineaDetalleCodigoComercialCodigo],[LineaDetalleCantidad],[LineaDetalleUnidadMedida],[LineaDetalleDetalle],[LineaDetallePrecioUnitario],[LineaDetalleMontoTotal]
	,[LineaDetalleMontoDescuento],[LineaDetalleNaturalezaDescuento],[LineaDetalleSubTotal],[LineaDetalleBaseImponible],[LineaDetalleImpuestoCodigo],[LineaDetalleImpuestoCodigoTarifa]
	,[LineaDetalleImpuestoTarifa],[LineaDetalleImpuestoFactor_IVA],[LineaDetalleImpuestoMonto],[LineaDetalleImpuestoMontoExportacion],[LineaDetalleImpuestoExoneracionTipoDocumento]
	,[LineaDetalleImpuestoExoneracionNumeroDocumento],[LineaDetalleImpuestoExoneracionNombreInstitucion],[LineaDetalleImpuestoExoneracionFechaEmision],[LineaDetalleImpuestoExoneracionPorcentajeExoneracion]
	,[LineaDetalleImpuestoExoneracionMontoExoneracion],[LineaDetalleImpuestoImpuestoNeto],[LineaDetalleMontoTotalLinea],[OtrosCargosTipoDocumento]
	,[OtrosCargosNumeroIdentidadTercero],[OtrosCargosNombreTercero],[OtrosCargosDetalle],[OtrosCargosPorcentaje],[OtrosCargosMontoCargo],[ResumenFacturaCodigoTipoMonedaCodigoMoneda]
	,[ResumenFacturaCodigoTipoMonedaTipoCambio],[ResumenFacturaTotalServGravados],[ResumenFacturaTotalServExentos],[ResumenFacturaTotalServExonerado]
	,[ResumenFacturaTotalMercanciasGravadas],[ResumenFacturaTotalMercanciasExentas],[ResumenFacturaTotalMercExonerada],[ResumenFacturaTotalGravado]
	,[ResumenFacturaTotalExento],[ResumenFacturaTotalExonerado],[ResumenFacturaTotalVenta],[ResumenFacturaTotalDescuentos],[ResumenFacturaTotalVentaNeta]
	,[ResumenFacturaTotalImpuesto],[ResumenFacturaTotalIVADevuelto],[ResumenFacturaTotalOtrosCargos],[ResumenFacturaTotalComprobante]
	,[NormativaNumeroResolucion],[NormativaFechaResolucion],[Respuesta],[InformacionReferenciaTipoDoc],[InformacionReferenciaNumero]
	,[InformacionReferenciaFechaEmision],[InformacionReferenciaCodigo],[InformacionReferenciaRazon],[Id_Reconciliacion]
	FROM [dbo].[FC_FACTURA_ELECTRONICA]
	WHERE N_FACTURA IN (@N_FACTURA) AND NumeroConsecutivoTipoComprobante NOT IN ('03','02') AND ID_EMPRESA = @ID_EMPRESA

	DELETE FROM FC_FACTURA_ELECTRONICA WHERE N_FACTURA IN (@N_FACTURA) AND NumeroConsecutivoTipoComprobante NOT IN ('03','02') AND ID_EMPRESA = @ID_EMPRESA

	UPDATE FC_NOTIFICACIONES
	SET ESTADO = 1
	 WHERE NODOCUMENTO IN (@N_FACTURA) AND TIPODOCUMENTO = 'FACTURA' AND ESTADO = 2

	--Contablidad

	EXECUTE CN_SP_ANULAR_ASIENTO @ID_ASIENTO, @ID_EMPRESA, @FECHA, 'Anu', @ID_USUARIO, @FECHA	

END
	 
END


IF NOT EXISTS (SELECT NAME FROM sys.objects WHERE TYPE = 'P' AND NAME = 'BKO_INV_InsertCraditNote')
  BEGIN
	EXEC('CREATE PROCEDURE [dbo].[BKO_INV_InsertCraditNote] AS RETURN')
END
GO

ALTER PROCEDURE [dbo].[BKO_INV_InsertCraditNote]
	@Id_Reconciliacion int,
	@Id_Empresa int,
	@Id_TipoClienteProveedor varchar(50),
	@CodigoClienteProveedor varchar(100),
	@COD_MONEDA int,
	@TipoCambio decimal(18,2),
	@Monto decimal(18,2),
	@Observacion varchar(500),
	@Estado varchar(50),
	@FechaSistema datetime,
	@Fecha datetime,
	@Rubro int,
	@USER_MODIFICA int,
	@N_FACTURA int,
	@AccionNotaCredito varchar(100),
	@MONTOFACTURADOLARES decimal(18,2),
	@MONTOFACTURACOLONES decimal(18,2),
	@COD_ASIENTO varchar(80),
	@AplicarFacturaElectronica int
AS

BEGIN TRANSACTION;

BEGIN TRY

IF(@TipoCambio = 0)
BEGIN

	SELECT @TipoCambio = TIPO_CAMBIO_VENTA FROM CN_TIPO_CAMBIO WHERE ID_EMPRESA = @Id_Empresa AND COD_MONEDA = '840'

END

DECLARE @VALIDARMONTO varchar(10), @MontoNuevo decimal(18,2), @COD_NOTACREDITO int

SELECT @VALIDARMONTO = 'False', @MontoNuevo = 0

IF (@Id_Reconciliacion <> 0)
BEGIN
	SELECT @COD_NOTACREDITO = COD_NOTACREDITO FROM CN_RECONCIALIACION WHERE Id_Reconciliacion = @Id_Reconciliacion
END
ELSE
BEGIN
	SELECT @COD_NOTACREDITO = ISNULL(MAX(COD_NOTACREDITO),0) + 1 FROM CN_RECONCIALIACION
END

IF(@AccionNotaCredito <> 'Aplicar')
BEGIN
	
	INSERT INTO [dbo].[CN_RECONCIALIACION]
           ([Id_Empresa]
           ,[Id_TipoClienteProveedor]
           ,[CodigoClienteProveedor]
           ,[COD_MONEDA]
           ,[TipoCambio]
           ,[Monto]
           ,[Observacion]
           ,[Estado]
           ,[FechaSistema]
           ,[Fecha]
           ,[FEC_MODIFICA]
           ,[USER_MODIFICA]
           ,[Rubro]
           ,[N_FACTURA]
		   ,[COD_NOTACREDITO]
		   ,[Aplicacion]
		   ,[COD_ASIENTO])
     VALUES
           (@Id_Empresa
           ,@Id_TipoClienteProveedor
           ,@CodigoClienteProveedor
           ,@COD_MONEDA
           ,@TipoCambio
           ,@Monto
           ,@Observacion
           ,@Estado
           ,@FechaSistema
           ,@Fecha
           ,GETDATE()
           ,@USER_MODIFICA
           ,@Rubro
           ,@N_FACTURA
		   ,@COD_NOTACREDITO
		   ,''
		   ,@COD_ASIENTO)

	SELECT @Id_Reconciliacion = MAX(Id_Reconciliacion) FROM CN_RECONCIALIACION

	IF(@AccionNotaCredito = 'CrearAplicar')
	BEGIN
		IF(@COD_MONEDA = 188)
		BEGIN
			SELECT @MontoNuevo = @Monto - @MONTOFACTURACOLONES	
			IF (@MontoNuevo > 0)
			BEGIN
				SELECT @VALIDARMONTO = 'True'
			END
			ELSE
			BEGIN
				SELECT @VALIDARMONTO = 'False'
			END
		END
		ELSE
		BEGIN
			SELECT @MontoNuevo = @Monto - @MONTOFACTURADOLARES
			IF (@MontoNuevo > 0)
			BEGIN
				SELECT @VALIDARMONTO = 'True'
			END
			ELSE
			BEGIN
				SELECT @VALIDARMONTO = 'False'
			END
		END
	END
END
ELSE
BEGIN
	UPDATE CN_RECONCIALIACION
	SET [Id_Empresa] = @Id_Empresa
		,[Id_TipoClienteProveedor] = @Id_TipoClienteProveedor
		,[CodigoClienteProveedor] = @CodigoClienteProveedor
		,[COD_MONEDA] = @COD_MONEDA
		,[TipoCambio] = @TipoCambio
		,[Monto] = @Monto
		,[Observacion] = @Observacion
		,[Estado] = @Estado
		,[FechaSistema] = @FechaSistema
		,[Fecha] = @Fecha
		,[FEC_MODIFICA] = GETDATE()
		,[USER_MODIFICA] = @USER_MODIFICA
		,[Rubro] = @Rubro
		,[N_FACTURA] = @N_FACTURA
		,[COD_ASIENTO] = @COD_ASIENTO
	WHERE Id_Reconciliacion = @Id_Reconciliacion

	IF(@COD_MONEDA = 188)
	BEGIN
		SELECT @MontoNuevo = @Monto - @MONTOFACTURACOLONES
		IF (@MontoNuevo > 0)
		BEGIN
			SELECT @VALIDARMONTO = 'True'
		END
		ELSE
		BEGIN
			SELECT @VALIDARMONTO = 'False'
		END
	END
	ELSE
	BEGIN
		SELECT @MontoNuevo = @Monto - @MONTOFACTURADOLARES
		IF (@MontoNuevo > 0)
		BEGIN
			SELECT @VALIDARMONTO = 'True'
		END
		ELSE
		BEGIN
			SELECT @VALIDARMONTO = 'False'
		END
	END
END

IF (@VALIDARMONTO = 'True')
BEGIN
	INSERT INTO [dbo].[CN_RECONCIALIACION]
			([Id_Empresa]
			,[Id_TipoClienteProveedor]
			,[CodigoClienteProveedor]
			,[COD_MONEDA]
			,[TipoCambio]
			,[Monto]
			,[Observacion]
			,[Estado]
			,[FechaSistema]
			,[Fecha]
			,[FEC_MODIFICA]
			,[USER_MODIFICA]
			,[Rubro]
			,[N_FACTURA]
			,[COD_NOTACREDITO]
			,[COD_ASIENTO])
		VALUES
			(@Id_Empresa
			,@Id_TipoClienteProveedor
			,@CodigoClienteProveedor
			,@COD_MONEDA
			,0
			,@MontoNuevo
			,@Observacion
			,'Pendiente'
			,@FechaSistema
			,@Fecha
			,GETDATE()
			,@USER_MODIFICA
			,@Rubro
			,0
			,@COD_NOTACREDITO
			,'')

			UPDATE CN_RECONCIALIACION
			SET Monto = @Monto - @MontoNuevo
			WHERE Id_Reconciliacion = @Id_Reconciliacion

			UPDATE CN_RECONCIALIACION
			SET Aplicacion = 'Parcial'
			WHERE COD_NOTACREDITO = @COD_NOTACREDITO
END
ELSE
BEGIN
			UPDATE CN_RECONCIALIACION
			SET Aplicacion = 'Total'
			WHERE COD_NOTACREDITO = @COD_NOTACREDITO
END

IF(@AccionNotaCredito <> 'Crear')
BEGIN

	INSERT INTO FC_FACTURA_NOTACREDITO_BITACORA
	SELECT 
	ID_EMPRESA,
	N_FACTURA,
	USUARIO,
	CAJA_ID,
	CLIENTE,
	FECHA,
	MONTOGRAVADO,
	MONTOEXENTO,
	IMPUESTOADUANAS,
	IMPUESTOVENTAS,
	SUBTOTAL,
	DESCUENTO,
	TOTAL,
	TOTALLOCAL,
	PAGADO,
	CAMBIO,
	FORMAPAGO_ID,
	ESTADO,
	SALDO,
	SALDOLOCAL,
	NOTA
	FROM FC_FACTURA
	WHERE N_FACTURA = @N_FACTURA

	DECLARE @SALDOLOCAL decimal(18,3),
	@SALDO decimal(18,3)
	
	SELECT
	@SALDOLOCAL = CASE WHEN @COD_MONEDA = 188 THEN CONVERT(decimal(18,2),SALDOLOCAL - @Monto) ELSE CONVERT(decimal(18,2),SALDOLOCAL - (@Monto * @TipoCambio)) END,
	@SALDO = CASE WHEN @COD_MONEDA = 188 THEN CONVERT(decimal(18,2),SALDO - (@Monto / @TipoCambio)) ELSE CONVERT(decimal(18,2),SALDO - @Monto) END
	FROM FC_FACTURA
	WHERE N_FACTURA = @N_FACTURA
	
	IF (@SALDOLOCAL < 0)
	BEGIN
		 SELECT @SALDOLOCAL = 0
		 SELECT @SALDO = 0
	END
	
	IF (@SALDO < 0)
	BEGIN
		 SELECT @SALDOLOCAL = 0
		 SELECT @SALDO = 0
	END

	IF(@Observacion <> 'Factura Electronica Anulada')
	BEGIN
	
		UPDATE FC_FACTURA
		SET 
		SALDOLOCAL = @SALDOLOCAL,
		SALDO = @SALDO,
		PAGADO = TOTAL - @SALDO
		WHERE N_FACTURA = @N_FACTURA
	
		UPDATE FC_FACTURA
		SET
		ESTADO = 2 -- SE MARCA COMO PAGADA CUANDO EL SALDO QUEDA EN 0.
		WHERE N_FACTURA = @N_FACTURA
		AND SALDO = 0

	END
	
	IF(@AplicarFacturaElectronica <> 1)
	BEGIN
		IF (SELECT COUNT(1) FROM FC_FACTURA_ELECTRONICA 
		WHERE N_FACTURA = @N_FACTURA AND ID_EMPRESA = 2 AND Procesada = 1 AND Respuesta = 'OK-aceptado' AND NumeroConsecutivoTipoComprobante IN ('01','04')) >= 1
		BEGIN
			EXEC FC_SP_CARGARFACTURAELECTRONICA_NOTA_CREDITO @N_FACTURA,@ID_EMPRESA,@Id_Reconciliacion
		END
	END

END

END TRY

BEGIN CATCH
    INSERT INTO CN_RECONCIALIACION_ERROR_BD
		SELECT
		@N_FACTURA, 
        ERROR_NUMBER() AS ErrorNumber
        ,ERROR_SEVERITY() AS ErrorSeverity
        ,ERROR_STATE() AS ErrorState
        ,ERROR_PROCEDURE() AS ErrorProcedure
        ,ERROR_LINE() AS ErrorLine
        ,ERROR_MESSAGE() AS ErrorMessage,
		@Id_Reconciliacion,
		GETDATE()
END CATCH;

IF @@TRANCOUNT > 0
    COMMIT TRANSACTION;



	IF NOT EXISTS (SELECT NAME FROM sys.objects WHERE TYPE = 'P' AND NAME = 'BKO_GetPaymentInfo')
  BEGIN
	EXEC('CREATE PROCEDURE [dbo].[BKO_GetPaymentInfo] AS RETURN')
END
GO

ALTER PROCEDURE [dbo].[BKO_GetPaymentInfo]
    @CompanyId INT,
    @PaymentId INT
AS
BEGIN
    SET NOCOUNT ON;
		SELECT 
		P.ID, 
		P.FECHA AS PaymentDate, 
		P.USUARIO AS [User], 
		P.PAGADO AS Paid, 
		F.N_FACTURA AS InvoiceNumber, 
		F.FECHA AS InvoiceDate, 
		F.TOTAL AS Total, 
		P.COD_MONEDA,
		CASE P.COD_MONEDA
			WHEN 840 THEN 'DOLLAR'
			WHEN 188 THEN 'COLONES'
			ELSE 'UNKNOWN'
		END AS Currency,
		F.TOTALLOCAL AS LocalTotal, 
		F.SALDO AS Balance, 
		F.SALDOLOCAL AS LocalBalance,
		EF.DESCRIPCION AS Status,
		P.PAGADO_COMISIONBANCARIA AS PaidBankCommission,
		P.PAGADO_IMPUESTOVENTAS AS PaidSalesTax,
		P.PAGADO_ADELANTORENTA AS PaidAdvanceRental,
		P.COMISIONBANCARIA AS BankCommission,
		P.IMPUESTOVENTAS AS SalesTax,
		P.ADELANTORENTA AS AdvanceRental,
		P.TIPO_CAMBIO_VENTA AS ExchangeRate
	FROM FC_PAGO P
	INNER JOIN FC_PAGOFACTURAS PF
		ON P.ID_EMPRESA = PF.ID_EMPRESA AND P.ID = PF.IDPAGO
	INNER JOIN FC_FACTURA F
		ON PF.ID_EMPRESA = F.ID_EMPRESA AND PF.N_FACTURA = F.N_FACTURA
	INNER JOIN FC_ESTADOFACTURA EF 
		ON EF.ID = P.ESTADO
	WHERE P.ID_EMPRESA = @CompanyId AND P.ID = @PaymentId

END

IF NOT EXISTS (SELECT NAME FROM sys.objects WHERE TYPE = 'P' AND NAME = 'BKO_INV_GenerateAccountingEntry')
  BEGIN
	EXEC('CREATE PROCEDURE [dbo].[BKO_INV_GenerateAccountingEntry] AS RETURN')
END
GO

ALTER PROCEDURE [dbo].[BKO_INV_GenerateAccountingEntry]
@ID_EMPRESA INT,
@FEC_PERIODO DATE,
@FEC_ASIENTO Datetime,
@DET_ASIENTO VARCHAR(200),
@IND_ESTADO VARCHAR(5),
@COD_SISTEMA_ORIGEN VARCHAR(50),
@IND_SISTEMA VARCHAR(50),
@FEC_INCLUSION DATE,
@USER_INCLUSION int
AS
BEGIN

SET NOCOUNT ON

BEGIN TRY

	DECLARE @COD_ASIENTO VARCHAR(80)

	SELECT @COD_ASIENTO = MAX(CONVERT(int,COD_ASIENTO)) + 1 FROM CN_ASIENTO

	IF(SELECT COUNT(1) FROM CN_ASIENTO WHERE COD_ASIENTO = @COD_ASIENTO) > 0
	BEGIN
		 SELECT @COD_ASIENTO = MAX(CONVERT(int,COD_ASIENTO)) + 1 FROM CN_ASIENTO
	END
	
	INSERT INTO CN_ASIENTO (ID_EMPRESA, COD_ASIENTO, FEC_PERIODO, FEC_ASIENTO, DET_ASIENTO, IND_ESTADO, COD_SISTEMA_ORIGEN, IND_SISTEMA, FEC_INCLUSION, USER_INCLUSION)
	VALUES(@ID_EMPRESA, @COD_ASIENTO, @FEC_PERIODO, @FEC_ASIENTO, @DET_ASIENTO, @IND_ESTADO, @COD_SISTEMA_ORIGEN, @IND_SISTEMA, @FEC_INCLUSION, @USER_INCLUSION) 

	SELECT @COD_ASIENTO AS COD_ASIENTO
	RETURN @COD_ASIENTO

END TRY

BEGIN CATCH
		INSERT INTO CN_ASIENTO_ERROR_BD
		SELECT
		@COD_ASIENTO, 
        ERROR_NUMBER() AS ErrorNumber
        ,ERROR_SEVERITY() AS ErrorSeverity
        ,ERROR_STATE() AS ErrorState
        ,ERROR_PROCEDURE() AS ErrorProcedure
        ,ERROR_LINE() AS ErrorLine
        ,ERROR_MESSAGE() AS ErrorMessage,
		0,
		GETDATE()

END CATCH;

END


IF NOT EXISTS (SELECT NAME FROM sys.objects WHERE TYPE = 'P' AND NAME = 'BKO_INV_GenerateAccountingEntry_Invoice')
  BEGIN
	EXEC('CREATE PROCEDURE [dbo].[BKO_INV_GenerateAccountingEntry_Invoice] AS RETURN')
END
GO
ALTER PROCEDURE [dbo].[BKO_INV_GenerateAccountingEntry_Invoice]
@ID_EMPRESA INT,
@COD_ASIENTO VARCHAR(80),
@N_FACTURA INT
AS

INSERT INTO CN_ASIENTO_FACTURA VALUES (@ID_EMPRESA,@COD_ASIENTO,@N_FACTURA)


IF NOT EXISTS (SELECT NAME FROM sys.objects WHERE TYPE = 'P' AND NAME = 'BKO_INV_SelectTemplateAccount')
  BEGIN
	EXEC('CREATE PROCEDURE [dbo].[BKO_INV_SelectTemplateAccount] AS RETURN')
END
GO
ALTER PROCEDURE [dbo].[BKO_INV_SelectTemplateAccount]
@ID_EMPRESA INT,
@COD_MODULO VARCHAR(10),
@COD_PLANTILLA INT
AS
BEGIN
	SELECT 
	cc.ID_EMPRESA,
	cc.NUM_CUENTA,
	COD_CUENTA,
	NOM_CUENTA,
	COD_MONEDA,
	CUENTA,
	CASE WHEN MONEDA = 'COLONES' THEN 'Colones' ELSE 'Dolares' END AS MONEDA,
	CLIENTE,
	cpd.IND_DEBCRE,
	cpd.NUM_LINEA
	FROM CN_PLANTILLA cp
	INNER JOIN CN_PLANTILLA_DETALLE cpd
	ON cp.ID_EMPRESA = cpd.ID_EMPRESA
	AND cp.COD_MODULO = cpd.COD_MODULO
	AND cp.COD_PLANTILLA = cpd.COD_PLANTILLA
	INNER JOIN CN_VW_SELECCIONA_CUENTA_HIJO cc
	ON cp.ID_EMPRESA = cc.ID_EMPRESA
	AND cpd.NUM_CUENTA = cc.NUM_CUENTA
	WHERE cp.ID_EMPRESA = @ID_EMPRESA 
	AND cp.COD_MODULO = @COD_MODULO 
	AND cp.COD_PLANTILLA = @COD_PLANTILLA	
END


-- Insert Accounting Detail
IF NOT EXISTS (SELECT NAME FROM sys.objects WHERE TYPE = 'P' AND NAME = 'BKO_INV_InsertAccountingDetail')
  BEGIN
	EXEC('CREATE PROCEDURE [dbo].[BKO_INV_InsertAccountingDetail] AS RETURN')
END
GO
ALTER PROCEDURE [dbo].[BKO_INV_InsertAccountingDetail]
@ID_EMPRESA INT,
@COD_ASIENTO VARCHAR(80),
@FEC_PERIODO DATE,
@NUM_LINEA_ASIENTO INT,
@MONTO_MOV FLOAT,
@NUM_CUENTA VARCHAR(50),
@IND_DEBCRE VARCHAR(5),
@MON_TIPO_CAMBIO FLOAT,
@MONTO_ORIGINAL FLOAT,
@MONEDA_ORIGINAL VARCHAR(5),
@COD_CLIENTE VARCHAR(20),
@CIERRE_ASIENTO VARCHAR(80)
AS
BEGIN

BEGIN TRY

	DECLARE @FEC_PERIODO_ASIENTO datetime

	SELECT @FEC_PERIODO_ASIENTO = FEC_PERIODO FROM CN_ASIENTO WHERE COD_ASIENTO = @COD_ASIENTO

	If @COD_CLIENTE = ''
		BEGIN
		Insert into CN_ASIENTO_DETALLE (ID_EMPRESA, COD_ASIENTO, FEC_PERIODO, NUM_LINEA_ASIENTO, MONTO_MOV, NUM_CUENTA, IND_DEBCRE, MON_TIPO_CAMBIO, MONTO_ORIGINAL, MONEDA_ORIGINAL)
		VALUES(@ID_EMPRESA, @COD_ASIENTO, @FEC_PERIODO_ASIENTO, @NUM_LINEA_ASIENTO, @MONTO_MOV, @NUM_CUENTA, @IND_DEBCRE, @MON_TIPO_CAMBIO, @MONTO_ORIGINAL, @MONEDA_ORIGINAL) 
		END
	ELSE
		BEGIN
		Insert into CN_ASIENTO_DETALLE (ID_EMPRESA, COD_ASIENTO, FEC_PERIODO, NUM_LINEA_ASIENTO, MONTO_MOV, NUM_CUENTA, IND_DEBCRE, MON_TIPO_CAMBIO, MONTO_ORIGINAL, MONEDA_ORIGINAL, COD_CLIENTE)
		VALUES(@ID_EMPRESA, @COD_ASIENTO, @FEC_PERIODO_ASIENTO, @NUM_LINEA_ASIENTO, @MONTO_MOV, @NUM_CUENTA, @IND_DEBCRE, @MON_TIPO_CAMBIO, @MONTO_ORIGINAL, @MONEDA_ORIGINAL, @COD_CLIENTE) 
		END

	--It is validated that the detailed amounts of the Entry are square.
	--If this is the case, the Entry field is updated to True.
	SET @CIERRE_ASIENTO = dbo.CN_FN_VALIDAR_APLICAR_ASIENTO(@ID_EMPRESA, @COD_ASIENTO, @FEC_PERIODO_ASIENTO)
	IF @CIERRE_ASIENTO = 'Aplicado'
		BEGIN
			--The CompleteClosings field is updated--
			UPDATE CN_ASIENTO SET CUADRADO = 1 
			WHERE ID_EMPRESA = @ID_EMPRESA	AND COD_ASIENTO = @COD_ASIENTO AND FEC_PERIODO = @FEC_PERIODO_ASIENTO
		END
	ELSE
		BEGIN
			UPDATE CN_ASIENTO SET CUADRADO = 0 
			WHERE ID_EMPRESA = @ID_EMPRESA	AND COD_ASIENTO = @COD_ASIENTO AND FEC_PERIODO = @FEC_PERIODO_ASIENTO
		END

END TRY

BEGIN CATCH
		INSERT INTO CN_ASIENTO_ERROR_BD
		SELECT
		@COD_ASIENTO, 
        ERROR_NUMBER() AS ErrorNumber
        ,ERROR_SEVERITY() AS ErrorSeverity
        ,ERROR_STATE() AS ErrorState
        ,ERROR_PROCEDURE() AS ErrorProcedure
        ,ERROR_LINE() AS ErrorLine
        ,ERROR_MESSAGE() AS ErrorMessage,
		0,
		GETDATE()

END CATCH;

END



IF NOT EXISTS (SELECT NAME FROM sys.objects WHERE TYPE = 'P' AND NAME = 'BKO_INV_SelectTemplateAccount')
  BEGIN
	EXEC('CREATE PROCEDURE [dbo].[BKO_INV_SelectTemplateAccount] AS RETURN')
END
GO
ALTER PROCEDURE [dbo].[BKO_INV_SelectTemplateAccount]
@ID_EMPRESA INT,
@COD_MODULO VARCHAR(10),
@COD_PLANTILLA INT
AS
BEGIN
	SELECT 
	cc.ID_EMPRESA as CompanyId,
	cc.NUM_CUENTA as AccountNumber,
	COD_CUENTA as AccountCode,
	NOM_CUENTA as AccountName,
	COD_MONEDA as CurrencyCode,
	CUENTA as Account,
	CASE WHEN MONEDA = 'COLONES' THEN 'Colones' ELSE 'Dolares' END AS CurrencyName,
	CLIENTE as Client,
	cpd.IND_DEBCRE as DebitCreditFlag,
	cpd.NUM_LINEA as LineNumber
	FROM CN_PLANTILLA cp
	INNER JOIN CN_PLANTILLA_DETALLE cpd
	ON cp.ID_EMPRESA = cpd.ID_EMPRESA
	AND cp.COD_MODULO = cpd.COD_MODULO
	AND cp.COD_PLANTILLA = cpd.COD_PLANTILLA
	INNER JOIN CN_VW_SELECCIONA_CUENTA_HIJO cc
	ON cp.ID_EMPRESA = cc.ID_EMPRESA
	AND cpd.NUM_CUENTA = cc.NUM_CUENTA
	WHERE cp.ID_EMPRESA = @ID_EMPRESA 
	AND cp.COD_MODULO = @COD_MODULO 
	AND cp.COD_PLANTILLA = @COD_PLANTILLA	
END


IF NOT EXISTS (SELECT NAME FROM sys.objects WHERE TYPE = 'P' AND NAME = 'BKO_INV_ValidateAccountingEntry')
  BEGIN
	EXEC('CREATE PROCEDURE [dbo].[BKO_INV_ValidateAccountingEntry] AS RETURN')
END
GO
ALTER PROCEDURE [dbo].[BKO_INV_ValidateAccountingEntry]
@ID_EMPRESA INT,
@COD_ASIENTO VARCHAR(80)
AS
BEGIN
	--We consult the Entry if the field CierreCompleto is true
	SELECT ISNULL(A.CUADRADO,0) AS CUADRADO FROM CN_ASIENTO A
	WHERE A.ID_EMPRESA = @ID_EMPRESA --AND A.FEC_PERIODO =@FECHA_PERIODO
	AND COD_ASIENTO = @COD_ASIENTO
END


IF NOT EXISTS (SELECT NAME FROM sys.objects WHERE TYPE = 'P' AND NAME = 'BKO_INV_ApplyAccountingEntry')
  BEGIN
	EXEC('CREATE PROCEDURE [dbo].[BKO_INV_ApplyAccountingEntry] AS RETURN')
END
GO
ALTER PROCEDURE [dbo].[BKO_INV_ApplyAccountingEntry]
@ID_EMPRESA INT,
@COD_ASIENTO VARCHAR(80)
AS
BEGIN
	--Finally, we update the Entry by changing its status to Applied.
	UPDATE CN_ASIENTO SET IND_ESTADO = 'Apli' 
	WHERE ID_EMPRESA = @ID_EMPRESA AND COD_ASIENTO = @COD_ASIENTO --AND FEC_PERIODO = @FEC_PERIODO
	
END

