export enum PermissionsEnum {
  'ClientCategories' = 'CIA_CLIENTCATEGORY',
  'Commodities' = 'CIA_COMMODITY',
  'Companies' = 'CIA_COMPANY',
  'PackageStatus' = 'CIA_PACKAGESTATUS',
  'Customers' = 'CTM_CUSTOMERS',
  'Areas' = 'GEN_AREAS',
  'Cashiers' = 'GEN_CASHIERS',
  'ControlCodes' = 'GEN_CONTROLCODES',
  'Countries' = 'GEN_COUNTRIES',
  'CustomerPayTypes' = 'GEN_CUSTPAYTYPES',
  'DocumentTypes' = 'GEN_DOCUMENTTYPE',
  'ShippingWayTypes' = 'GEN_SHIPPINGWAY',
  'States' = 'GEN_STATES',
  'Zones' = 'GEN_ZONES',
  'OpenClosedManifests' = 'MNF_MANIFEST_OPEN',
  'Manifests' = 'MNF_MANIFESTS',
  'AirClassify' = 'MNF_AIR_CLASSIFY',
  'Packages' = 'PKG_PACKAGE',
  'PackageEvents' = 'PKG_EVENTS',
  'PackageCategory' = 'PKG_CATEGORY',
  'PackingPackagesAeropost' = 'PKG_PACKAGES_AEROPOST',
  'Locations' = 'SUP_LOCATIONS',
  'Suppliers' = 'SUP_SUPPLIER',
  'Roles' = 'USR_ROLES',
  'Users' = 'USR_USERS',
  'DocumentPayTypes' = 'CIA_DOCUMENTPAYTYPES',
  'PackageClassify' = 'PKG_CLASSIFY',
  'PaymentTypes' = 'CIA_PAYMENTTYPES',
  'PackageLogNotes' = 'PKG_PACKAGE',
  'PackageNotes' = 'PKG_NOTES',
  'PackingPackageCourier' = 'PKG_PACKING_COURIER',
  'PackingPackageConsolidate' = 'PKG_PACKING_CONSOLIDATE',
  'PackingPackageAeropost' = 'PKG_PACKING_AEROPOST',
  'InvoiceHistory'='INV_INVOICE_HISTORY',
  'GenerateReport'='INV_REPORT_GENERATION',
  'PackageScanning' = 'MNF_PACKAGE_SCANNING',
  'PackagePreStudy' = 'PKG_PRE_STUDY',
  'PackageAssignPrices' = 'PKG_ASSIGN_PRICES',
  'DeliveryProof'='DELIVERY_PROOF',
  'ManifestReports'='REPORTS',
  'PointOfSale'='PAY_POINT_OF_SALE',
  'CustomerService'='CUSTOMER_SERVICE',
  'GenerateInvoice'='GENERATE_INVOICE',
  'InvoiceSummary'='INVOICE_SUMMARY',
  'CreditPending'='CREDIT_PENDING',
  'ReOpenRoadmap'='MNF_REOPEN_ROADMAP',
  'ManagePackagesRoute'='MNF_MANAGE_PACKAGE_ROUTE',
  'CUST_COSTOMER_SERVICE'='CUST_COSTOMER_SERVICE',
  'RPT_COUR_DECONSOLIDATION'='RPT_COUR_DECONSOLIDATION',
  'RPT_CREDIT_PENDING'='RPT_CREDIT_PENDING',
  'RPT_DETAILED_BILLING'='RPT_DETAILED_BILLING',
  'RPT_MNF_OBSERVATIONS'='RPT_MNF_OBSERVATIONS',
  'RPT_PND_MNF_PRE_STUDY'='RPT_PND_MNF_PRE_STUDY',
  'RPT_SUMMARY'='RPT_SUMMARY',
  'EnabledCredit'='CUST_ENABLED_CREDIT',
  'Purchases'='RPT_PURCHASES',
  'CustomsTaxes'='RPT_CUSTOMS_TAXES',
 'PackageInventory' = 'PKG_PACKAGE_INVENTORY',
  'PendingInvoice' = 'RPT_PENDING_INVOICES',
  'SalesDetail'= 'RPT_SALES_DETAIL',
  'ManifestReportByBag'='RPT_MNF_REPORT_BY_BAG',
  'CourierConsolidated'='RPT_COURIER_CONSOLIDATED',
  'HasInvoiceMaintenance'='PKG_HAS_INVOICE_MAINTENANCE',
  'PriceImageMaintenance'='PKG_PRICE_IMAGE_MAINTENANCE',
  'LoadCustomsTaxex'='INV_LOAD_CUSTOMS_TAXEX',
  'AeropostMassUpload'='RPT_AEROPOST_MASS_UPLOAD'

  
} 

export enum PermissionActionEnum {
  'View' = 1,
  'Add' = 2,
  'Update' = 3,
  'Delete' = 4
}

